[package]
name = "multiplayer-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bevy_renet = {version = "0.0.11", features = ["serde"]}
bincode = "1.3.3"
renet = "0.0.15"
serde = "1.0.203"
